### ISSUE TITLE
Does not work with webpack 5?

### ISSUE THREAD

**Issue by TomStrepsil** [Chance722/webpack-chokidar-plugin#9]
> `TypeError: compiler.plugin is not a function`

...I assume this has not been updated for Webpack 5

**Comment by subatomicglue** [comment]
```
const WebpackChokidarPlugin = require('webpack-chokidar-plugin')

...
module.exports = {
  plugins: [
    new WebpackChokidarPlugin({
      watchFilePaths: [
        path.resolve(__dirname, 'src/**'),
      ],
    }),
  ],
  ...
}
```

```
[webpack-cli] TypeError: compiler.plugin is not a function
    at wepackChokidarPlugin.apply (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack-chokidar-plugin/lib/index.js:14:12)
    at createCompiler (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack/lib/webpack.js:76:12)
    at create (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack/lib/webpack.js:143:16)
    at webpack (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack/lib/webpack.js:167:32)
    at WebpackCLI.f [as webpack] (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack/lib/index.js:72:16)
    at WebpackCLI.createCompiler (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack-cli/lib/webpack-cli.js:1785:29)
    at async Command.<anonymous> (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/@webpack-cli/serve/lib/index.js:81:30)
    at async Command.parseAsync (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async Command.<anonymous> (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack-cli/lib/webpack-cli.js:1356:13)
    at async Command.parseAsync (/home/kevin/src/EOSLang/examples/ts-frontend/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
```
